### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by lbischof** [antoiner77/caddy-ansible#104]
See #103:
@joelnb wrote: 
> I would be happy to do this if that would be acceptable. I  have contributed before and I still use the module on some of my hosts.

@joelnb That would be awesome. I couldn't reach @antoiner77 though, so we would need to fork the project and update all the other places (ansible-galaxy etc).

@antoiner77 ping! could you add me as an admin on this Github repository?

**Comment by joelnb** [comment]
I would be happy to continue maintaining in this repo if @antoiner77 is happy to grant required privileges or fork it somewhere else and update this one one to point to the new version.

Just to be clear are you still interesting in contributing if/when you have the time? If so (and if forking is required) it might make sense to put it under an organisation where we could both easily have access.

**Comment by lbischof** [comment]
Sure, I would actually like to contribute more, so that would be great.

**Comment by joelnb** [comment]
Well I'm more than happy to help move to a new repo or just jump in on any issues/pull requests to write some code or review. Currently everything is working well for me so I haven't been trying to make any changes. I could have a look into the tests though if that would be helpful? I noticed an issue about that. They do seem to be enabled now but are failing.

**Comment by LorenzBischof** [comment]
I have created a new organization and added you as a member. We can continue here: https://github.com/caddy-ansible/caddy-ansible/issues/1
