### ISSUE TITLE
Can't bind on ports < 1024 in systemd

### ISSUE THREAD

**Issue by derimagia** [antoiner77/caddy-ansible#25]
Because of the condition: 
https://github.com/antoiner77/caddy-ansible/blob/ea15e0f125d3cc73697a3371ba4fc42e1e2f1266/tasks/main.yml#L70

I'm assuming this was for a reason - like the fact that systemd handles this but it's not working right now for Ubuntu 16 with systemd installed because of the permission issue.

**Comment by lbischof** [comment]
I just checked and it seems the relevant part was commented out. https://github.com/mholt/caddy/blob/master/dist/init/linux-systemd/caddy.service

**Comment by lbischof** [comment]
I'm not exactly sure why setcap is disabled for systemd. Did executing the command manually work for you?

**Comment by lbischof** [comment]
Fixed by c433db8
