### ISSUE TITLE
Add warning if email isn't set

### ISSUE THREAD

**Issue by lbischof** [antoiner77/caddy-ansible#27]
We should add a warning when the email isn't set. I think checking if the `tls` option is present would be enough. See #26 

https://caddyserver.com/docs/automatic-https
https://caddyserver.com/docs/tls

**Comment by LorenzBischof** [comment]
Closing because the repository has moved to https://github.com/caddy-ansible/caddy-ansible If this is still an issue, please reopen the issue in the new repository.
