### ISSUE TITLE
Checking for binding capabilities isn't working

### ISSUE THREAD

**Issue by Depado** [antoiner77/caddy-ansible#29]
Hey there !

First of all, thanks for the playbook it's working fine and automates a lot of stuff ! 🎉 

I noticed when I executed a playbook that Caddy wasn't able to bind to port 80/443, so I had to run the `setcap` command manually. Is it possible the test is broken ? 

I ran the playbook against a new debian machine.

**Comment by lbischof** [comment]
Did you try with the newest version? 2.0.1? It was deactivated for systemd users before, because I though the service file allowed it.

**Comment by Depado** [comment]
Oh, maybe I did not update, indeed. I'll give it a try and close the issue if it solves it. 
Also quick question : how do I add my email when calling the role ? (if it is possible)

**Comment by lbischof** [comment]
I added the email example everywhere: a199b3accd4b01a3b5defa035325c11e7b50ce3f

**Comment by Depado** [comment]
Oh I see ! I thought there was a way to customize the command line argument like shown in the docs : https://caddyserver.com/docs/cli

Thanks for the examples :D

**Comment by lbischof** [comment]
Was this issue resolved by updating to the newest version?

**Comment by Depado** [comment]
No idea yet, I noticed `ansible-galaxy` doesn't allow updates. I updated, but didn't try again, tell me if that works :)
