### ISSUE TITLE
Do not assume that init system is either systemd or upstart

### ISSUE THREAD

**Issue by lucafavatella** [antoiner77/caddy-ansible#37]
Script checks whether systemd binary is there, and [if not assumes upstart](https://github.com/antoiner77/caddy-ansible/blob/v2.0.2/tasks/main.yml#L53-L54). See [relevant script portion](https://github.com/antoiner77/caddy-ansible/blob/v2.0.2/tasks/main.yml#L48-L64).

Logic shall be enhanced with check for upstart binary, and if not found simply skip upstart as well.

The bottom line is that user of Ansible role may be using neither systemd nor upstart hence would prefer caddy-ansible role to skip init configuration/restart altogether if not recognized - rather than it assuming upstart.

**Comment by lbischof** [comment]
Do you have a valid use case? Are you using something else or has the check failed to identify the correct init system? Detecting init systems is very hard and only having one single check simplifies everything. If someone has something else we could maybe add manage_service?

**Comment by lucafavatella** [comment]
I have in mind to use runit inside Docker. I have not tried this role there yet.

**Comment by lbischof** [comment]
Ansible isn't suited for Docker usage. You should use one of the Caddy images from Dockerhub or write your own dockerfile. I will close this issue for now. Please reopen if you have an issue with the init systems.
