### ISSUE TITLE
Caddy archive passed from controller rather than downloaded

### ISSUE THREAD

**Issue by lucafavatella** [antoiner77/caddy-ansible#39]
At the moment caddy-ansible downloads the Caddy archive from the Web on the remote system (as opposed to the Ansible controller). In order to make the deployment more predictable, I am considering downloading Caddy on the Ansible controller and then copying it over.

Before I put effort on this, would you welcome such a contribution?

**Comment by lbischof** [comment]
I see where you're coming from. If it doesn't add any complexity then go ahead.

**Comment by LorenzBischof** [comment]
Closing because the repository has moved to https://github.com/caddy-ansible/caddy-ansible If this is still an issue, please reopen the issue in the new repository.
