### ISSUE TITLE
Caddy config passed as path to Jinja2 template rather than caddy_config string variable

### ISSUE THREAD

**Issue by lucafavatella** [antoiner77/caddy-ansible#45]
In projects I aim at trying to keep as separate repos / branches:
* Applications - including a version of the configuration file templated wrt e.g. domain names, IP addresses, TCP ports;
* Configuration of environments e.g. domain names, IP addresses, TCP ports;
* Application artefacts generation, application configuration template instantiation, provisioning, deployment and acceptance tests.

The current caddy-ansible role takes the Caddyfile as a string in a variable, that makes templating difficult.

Would you welcome a contribution that removes the caddy_config variable and replaces it with a caddy_config_template_path variable? As files not using Jinja2 syntax like `{{ X }}` are templates, such variable would implicitly enable copy of already-instantiated Caddyfile too. Of course the contribution shall update CI test and README.

**Comment by lbischof** [comment]
Just a thought: most Caddyfiles contain more than one line. Maybe it would be possible to split the string into lines `splitlines()` and count `|length > 1`? That way it would stay backward compatible and a user could choose a file or a string

**Comment by lucafavatella** [comment]
I am aware that more potential code paths call more test cases, and CI script does not have support for multiple test cases. I wonder if passing config as string is really something you want to keep.

**Comment by lucafavatella** [comment]
> Maybe it would be possible to split the string into lines splitlines() and count |length > 1?

I am not finding this `splitlines()` documented for Jinja2 in Ansible variables so if I find time I plan to remove the current caddy_config variable and define a caddy_config_path variable that is then handled with the Ansible template module.

**Comment by lbischof** [comment]
> I am aware that more potential code paths call more test cases
Good point
> I wonder if passing config as string is really something you want to keep.
I'm not sure if anyone is making use of it, so I don't know if we should delete it...

I think I'll let you decide, I have come to the conclusion that every option isn't perfect and can't decide which one is best...

**Comment by joelnb** [comment]
I think this feature is not actually needed because it can already be implemented at the playbook level. I have done this in my playbook and it works perfectly:

```
caddy_config: "{{ lookup('template', 'templates/Caddyfile-hostname.j2') }}"
```

This means that there is no need to add more complexity to the role & we can just recommend that people take this approach instead.

**Comment by lbischof** [comment]
Great idea! We should update the README. I'll do it in the next few days if you don't create a pullrequest till then.

**Comment by joelnb** [comment]
I made a quick pull request but feel free to do your own thing if you had something better in mind.
