### ISSUE TITLE
About licenses

### ISSUE THREAD

**Issue by Depado** [antoiner77/caddy-ansible#66]
Hey there,
I remembered that I read something about caddy's licenses recently (well not so recently but still)
https://caddyserver.com/blog/accouncing-caddy-commercial-licenses#urls

I think this will break the playbook once they effectively disallow the "no license parameter". I don't know they still plan to prevent this but it's worth checking and potentially offer a way to set a license in the playbook (and fallback to a personal license if none is provided)

**Comment by lbischof** [comment]
I currently don't have time to update this. Pull requests are greatly appreciated.

**Comment by joelnb** [comment]
I will have a go at this, doesn't look too hard & it does sound like the role will break without it at some point in the future.

**Comment by joelnb** [comment]
@Depado if you are able to test the pull request I made for this it would be very helpful.

**Comment by Depado** [comment]
I'll give it a try when I have some time :)
Thanks for your PR @joelnb !

**Comment by joelnb** [comment]
I think this could be closed now based on #67 being merged.
