### ISSUE TITLE
centos7: service start fails

### ISSUE THREAD

**Issue by lbischof** [antoiner77/caddy-ansible#7]
service start fails when running the playbook a second time. I didn't check if it really worked the first time.

**Comment by lbischof** [comment]
Systemd couldn't access the working directory because it didn't exist

**Comment by belmarca** [comment]
It's still failing. I can't get the service to work on a fresh CentOS 7.1 box. I'm working on a fix but I don't really know where the problem is.

**Comment by lbischof** [comment]
Thanks for reporting. The cause is usually either Caddy that can't start, systemd can't write to a certain file or systemd doesn't realize that the service is already running. I'll try and figure out what went wrong.

**Comment by belmarca** [comment]
It works fine now. I'll let you know if I am faced with other errors.

**Comment by lbischof** [comment]
Pullrequest #18 should fix this, because it uses official service files.

**Comment by lbischof** [comment]
We are using the official service files. Issues should be reported upstream.
