### ISSUE TITLE
Lock version

### ISSUE THREAD

**Issue by paulfantom** [antoiner77/caddy-ansible#73]
It would be nice to have variable like `caddy_version` by which we could provide which caddy version we want to install. Such feature is crucial on production systems, so we won't have downtimes by upgrading to untested (latest) version, like it happend with caddy 0.10.13 which broke letsencrypt.

**Comment by lbischof** [comment]
You can set `caddy_update: no` and then Caddy will not be updated after it
is deployed. Is there a url we could use to download a specific version?

**Comment by paulfantom** [comment]
Yeah, I know about `caddy_update: no`, but right now I would like to revert to 0.10.12 and it is not possible.

I don't know if there is an url to download specific version.

**Comment by joelnb** [comment]
I think this would be very nice to have but I'm not sure how feasible it is at the moment. It is possible to get all of the versions of caddy from the github repo releases page but this only includes the vanilla version of caddy (with no plugins). I'm not aware of anywhere online you can download old versions with plugins.

**Comment by LorenzBischof** [comment]
Closing because the repository has moved to https://github.com/caddy-ansible/caddy-ansible If this is still an issue, please reopen the issue in the new repository.
