### ISSUE TITLE
What's the License?

### ISSUE THREAD

**Issue by paulfantom** [antoiner77/caddy-ansible#74]
I just realized that this project doesn't have a license mentioned anywhere. There is no license section in readme file and there is no license file.
This means that from legal point of view there is a very limited scope on what can be done with this project (via https://choosealicense.com/no-permission/).

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

I propose to add [MIT license](https://opensource.org/licenses/MIT).

**Comment by lbischof** [comment]
Thanks, I didn't realize. I think MIT is fine and I'll add it when I get
home

**Comment by lbischof** [comment]
Fixed with ebdf1e8863b22680a5f0de888f4d92fe5aae6898
