### ISSUE TITLE
Logs don't work

### ISSUE THREAD

**Issue by chrisglass** [antoiner77/caddy-ansible#79]
It looks like the systemd configuration for logs doesn't work at all (/var/log/caddy/ remains empty).

Having it work would be tremendously useful for both operations and role debugging.

**Comment by chrisglass** [comment]
I will send a PR fixing this as I have a solution.

**Comment by LorenzBischof** [comment]
Closing because the repository has moved to https://github.com/caddy-ansible/caddy-ansible If this is still an issue, please reopen the issue in the new repository.
