### ISSUE TITLE
License type is required

### ISSUE THREAD

**Issue by tsvetann** [antoiner77/caddy-ansible#88]
Looks like caddy now require to specify explicitly the license type=personal.

Look here:
`https://github.com/antoiner77/caddy-ansible/blob/master/tasks/main.yml#L33`

Error example:
`https://caddyserver.com/download/linux/amd64?plugins=http.cache,http.minify`
 
Correct example:
`https://caddyserver.com/download/linux/amd64?plugins=http.cache,http.minify&license=personal`

The actual error I get:
```
TASK [antoiner77.caddy : Download Caddy] *********************************************************************************************************************************
fatal: [mydomain.com]: FAILED! => {"changed": false, "dest": "/home/caddy/caddy.tar.gz", "msg": "Request failed", "response": "HTTP Error 400: Bad Request", "state": "absent", "status_code": 400, "url": "https://caddyserver.com/download/linux/amd64?plugins=http.cache,http.minify"}
	...
```

Config:
...
`caddy_license: personal`
...

**Comment by joelnb** [comment]
Are you using the master branch? This is meant to be handled by the 'Build request URLs' step because it has been required for a while.

I'm away at the moment but I should be able to look at it over the weekend if you are using the master branch.

**Comment by tsvetann** [comment]
Hi,

I am using the master but of the previous version. With the latest version works. My bad.
